### ISSUE TITLE
Fails with format <book> <chapter> - <end chapter>:<end verse>

### ISSUE THREAD

**Issue by mpnordland** [davisd/python-scriptures#5]
I'm using python-scriptures to parse sermon passages out of ID3 tags from the sermon mp3 files. I came across this passage: I Sam 28-28:2 which fails with the following trace:
````
Traceback (most recent call last):
  File "./mp3grabber.py", line 211, in <module>
    postSermon(u, tags)
  File "./mp3grabber.py", line 173, in postSermon
    sermon = sermon_tagger.tag_sermon(sermon, tags)     
  File "/home/micah/dev/fairwaypark/orgsermons.py", line 144, in tag_sermon
    raise e
  File "/home/micah/dev/fairwaypark/orgsermons.py", line 118, in tag_sermon
    book = extract_book(scriptures.extract(tags_text))
  File "/home/micah/dev/fairwaypark/scriptures/references.py", line 28, in extract
    references.append(normalize_reference(*r.groups()))
  File "/home/micah/dev/fairwaypark/scriptures/references.py", line 120, in normalize_reference
    or (chapter == end_chapter and end_verse < verse))):
TypeError: unorderable types: int() < NoneType()
````

**Comment by mpnordland** [comment]
This can be fixed with another special condition that sets verse to one if chapter and end_chapter are not None and verse is None. I'll have a pull request up directly.

**Comment by davisd** [comment]
Hello @mpnordland - thank you for submitting this issue.

I would expect that the reference cited would be written as either:

* I Sam 28:1-2
* I Sam 28:1-28:2

But regardless, this:

    scriptures.extract('I Sam 28-28:2')

should not throw an exception -  that needs fixed.

I see the benefit of this format in something spanning multiple chapters-
* I Sam 1-2:15

Thanks for bringing this issue to the project - I think it is a good idea.  I'll take a look at your pull request and work the format into the test suite.  The regex may need updated as well.

-David
